name: Windows Build 🏹

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Generate Project Files & BUILD
      run: ./Scripts/BuildAll.bat
