name: Windows Build 🏹

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Generate Electro Files
      run: ./Scripts/WindowsGenProjects.bat

    - name: Build ExampleApp
      run: |
        cd ExampleApp
        mkdir build
        cd build
        cmake --build . --target ALL_BUILD
        cd ..\..\

    - name: Build Electro
      run: |
        cd build
        msbuild -property:Configuration=Release,MultiProcessorCompilation=true -maxCpuCount -verbosity:minimal -noLogo Electro.sln